typography_spectrum: 0.4860365
color:
  saturation: 0.6772288
  brandStrength: 0.8984962
  rhythmicContrast: 0.6095597
  brandColors:
    - '#1F0000'
    - '#C38B3E'
    - '#DBA150'
    - '#702605'
    - '#A26718'
  lightness: 0.7588614
layout_spectrum: 0.7051557
name: 'djbassmonkey '
navigation:
  - name: My Music
    url: 'https://soundcloud.com/djbassmonkey/sets/new-compositions-fall-2015'
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Are you not entertained?
description: 'Do a little dance, make a little love. Get down tonight!'
